# https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/
version: "3"
services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.2.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9600:9600
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - opendistro_security.disabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
  logstash:
    image: logstash:6.8.3
    container_name: logstash
    volumes:
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
      - ./log:/var/log

volumes:
  es_data:
